appname: authextest

session: simple
logger: console
log: core

plugins:
    Auth::Extensible:
        realms:
            example:
                provider: Example
            config:
                provider: Config
                users:
                    - user: 'configuser'
                      pass: 'password'
                      name: 'Example user'
                      roles:
                        - TestPerson


show_errors: 1

